name: Release

on:
  workflow_call:
    inputs:
      image_name:
        required: false
        type: string
        default: ''
      image_digest:
        required: false
        type: string
        default: ''

jobs:
  exists:
    runs-on: ubuntu-latest

    outputs:
      release: ${{ steps.release.outputs.tag }}
      check: ${{ steps.check.outputs.exists }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v6.1.0

      - name: Get version for release tag
        id: release
        run: echo "tag=$(awk -F'[][]' '/^## \[v/{print $2; exit}' CHANGELOG.md)" >> "$GITHUB_OUTPUT"

      - name: Check if release already exists
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.release.outputs.tag }}
        run: |
          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          fi

  launch:
    needs: exists
    if: needs.exists.outputs.check != 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6.1.0

      - name: Prepare body file to release release_notes
        run: awk '/^## \[v/{n++; next} n==1' CHANGELOG.md | sed '/./,$!d' > /tmp/body.md
      
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v4.4.1

      - name: Get image name/digest
        id: digest
        env:
          NAME: ${{ inputs.image_name }}
          DIGEST: ${{ inputs.image_digest }}
        run: |
          if [[ $NAME == '' || $DIGEST == '' ]]; then
              IMG_TAG=$(head -n1 build/VERSION)
              IMG="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$IMG_TAG"
              NAME=$(docker buildx imagetools inspect $IMG --format '{{ .Manifest }}' | grep 'Name')
              DIGEST=$(docker buildx imagetools inspect $IMG --format '{{ .Manifest }}' | grep 'Digest')
              echo "man_name=$NAME" >> "$GITHUB_OUTPUT"
              echo "man_digest=$DIGEST" >> "$GITHUB_OUTPUT"
          else
              echo "man_name=$NAME" >> "$GITHUB_OUTPUT"
              echo "man_digest=$DIGEST" >> "$GITHUB_OUTPUT"
          fi

      - name: Add digest to body file
        env:
          NAME: ${{ steps.digest.outputs.man_name }}
          DIGEST: ${{ steps.digest.outputs.man_digest }}
        run: |
          echo -e "\n## Imagem" >> /tmp/body.md
          echo "\`\`\`text" >> /tmp/body.md
          echo "$NAME" >> /tmp/body.md
          echo "$DIGEST" >> /tmp/body.md
          echo "\`\`\`" >> /tmp/body.md

      - name: Create Release
        uses: ncipollo/release-action@v1.21.0
        env:
          RELEASE_TAG: ${{ needs.exists.outputs.release }}
        with:
          tag: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          bodyFile: /tmp/body.md
          commit: ${{ github.sha }}
